/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CompanyIcon: typeof import('./components/CompanyIcon.vue')['default']
    Footer: typeof import('./components/Footer/index.vue')['default']
    HotCompanies: typeof import('./components/HotCompanies.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    MarketBreadth: typeof import('./components/MarketBreadth.vue')['default']
    MarketBreath: typeof import('./components/MarketBreath.vue')['default']
    MomentumChart: typeof import('./components/MomentumChart.vue')['default']
    PortfolioChart: typeof import('./components/PortfolioChart/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeeMore: typeof import('./components/SeeMore.vue')['default']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TradingviewGadget: typeof import('./components/TradingviewGadget.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VolatileAsset: typeof import('./components/VolatileAsset.vue')['default']
    Waterfall: typeof import('./components/Waterfall/index.vue')['default']
  }
}
